title:              "Yuri’s Pouch"
tagline:            "Let’s become a K-beauty expert with Yuri"
email:              "yurispouch@gmail.com"
description:        "We share the latest information about the K-Beauty industry."
author:             "yuri"
baseurl:            "/"
url:                "https://yurispouch.com"
locale:             "en_US"
thumbnail:          "/img/thumb.jpeg"

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: yurispouch
